-- Data extracted from src/data/dropdownOptions.ts. The application should read
-- these values from public.lookup_options in production, not bundled source code.
insert into public.lookup_options (category, value, label, sort_order) values
  ('on_offshore', 'Onshore', 'Onshore', 1),
  ('on_offshore', 'Offshore', 'Offshore', 2),
  ('region_area', 'Western Desert', 'Western Desert', 1),
  ('region_area', 'Eastern Desert', 'Eastern Desert', 2),
  ('region_area', 'Gulf of Suez', 'Gulf of Suez', 3),
  ('region_area', 'Mediterranean / Nile Delta', 'Mediterranean / Nile Delta', 4),
  ('frac_vendor', 'Schlumberger', 'Schlumberger', 1),
  ('frac_vendor', 'Halliburton', 'Halliburton', 2),
  ('frac_vendor', 'Baker Hughes', 'Baker Hughes', 3),
  ('frac_vendor', 'Weatherford', 'Weatherford', 4),
  ('frac_vendor', 'Calfrac', 'Calfrac', 5),
  ('frac_vendor', 'Trican', 'Trican', 6),
  ('frac_vendor', 'Other', 'Other', 7),
  ('data_source', 'Live Database', 'Live Database', 1),
  ('data_source', 'Vendor Report', 'Vendor Report', 2),
  ('data_source', 'Scanned PDF', 'Scanned PDF', 3),
  ('data_source', 'Estimated', 'Estimated', 4),
  ('data_source', 'Critical for QC', 'Critical for QC', 5),
  ('technique', 'Hi-Way', 'Hi-Way', 1),
  ('technique', 'Conventional', 'Conventional', 2),
  ('technique', 'clear frac', 'clear frac', 3),
  ('technique', 'Hi-way/Clear frac', 'Hi-way/Clear frac', 4),
  ('lithology', 'Sandstone', 'Sandstone', 1),
  ('lithology', 'Carbonate', 'Carbonate', 2),
  ('lithology', 'Shale', 'Shale', 3),
  ('lithology', 'Siltstone', 'Siltstone', 4),
  ('lithology', 'Dolomite', 'Dolomite', 5),
  ('lithology', 'Limestone', 'Limestone', 6),
  ('lithology', 'Chalk', 'Chalk', 7),
  ('lithology', 'Mixed', 'Mixed', 8),
  ('well_type', 'Vertical', 'Vertical', 1),
  ('well_type', 'Deviated', 'Deviated', 2),
  ('well_type', 'Horizontal', 'Horizontal', 3),
  ('well_type', 'Multilateral', 'Multilateral', 4),
  ('availability', 'Available', 'Available', 1),
  ('availability', 'Not Available', 'Not Available', 2),
  ('job_type', 'Stimulation', 'Stimulation', 1),
  ('job_type', 'Acidizing', 'Acidizing', 2),
  ('job_type', 'Re-Frac', 'Re-Frac', 3),
  ('job_type', 'Initial Completion', 'Initial Completion', 4),
  ('job_type', 'Workover', 'Workover', 5),
  ('completion_type', 'Cemented Casing', 'Cemented Casing', 1),
  ('completion_type', 'Open Hole', 'Open Hole', 2),
  ('completion_type', 'Perforated Casing', 'Perforated Casing', 3),
  ('completion_type', 'Gravel Pack', 'Gravel Pack', 4),
  ('completion_type', 'Frack Pack', 'Frack Pack', 5),
  ('completion_type', 'Tubingless', 'Tubingless', 6),
  ('tubing_grade', 'J55', 'J55', 1),
  ('tubing_grade', 'K55', 'K55', 2),
  ('tubing_grade', 'L80', 'L80', 3),
  ('tubing_grade', 'N80', 'N80', 4),
  ('tubing_grade', 'P110', 'P110', 5),
  ('tubing_grade', 'Q125', 'Q125', 6),
  ('tubing_grade', 'Cr13', '13 Cr', 7),
  ('tubing_grade', 'Super Cr13', 'Super 13 Cr', 8),
  ('proppant_type', '20/40 White Sand', '20/40 White Sand', 1),
  ('proppant_type', '20/40 Brown Sand', '20/40 Brown Sand', 2),
  ('proppant_type', '30/50 White Sand', '30/50 White Sand', 3),
  ('proppant_type', '40/70 White Sand', '40/70 White Sand', 4),
  ('proppant_type', '20/40 Ceramic', '20/40 Ceramic', 5),
  ('proppant_type', '16/20 Ceramic', '16/20 Ceramic', 6),
  ('proppant_type', 'Resin Coated', 'Resin Coated', 7),
  ('proppant_type', 'Lightweight Proppant', 'Lightweight Proppant', 8),
  ('gel_type', 'Linear Gel 10 lb', 'Linear Gel 10 lb', 1),
  ('gel_type', 'Linear Gel 20 lb', 'Linear Gel 20 lb', 2),
  ('gel_type', 'Linear Gel 30 lb', 'Linear Gel 30 lb', 3),
  ('gel_type', 'Linear Gel 40 lb', 'Linear Gel 40 lb', 4),
  ('crosslinked_gel_type', 'Borate Crosslinked', 'Borate Crosslinked', 1),
  ('crosslinked_gel_type', 'Zirconate Crosslinked', 'Zirconate Crosslinked', 2),
  ('crosslinked_gel_type', 'Titanate Crosslinked', 'Titanate Crosslinked', 3),
  ('crosslinked_gel_type', 'Clear FRAC', 'Clear FRAC', 4),
  ('cost_unit', 'lb', 'lb', 1), ('cost_unit', 'gal', 'gal', 2),
  ('cost_unit', 'bbl', 'bbl', 3), ('cost_unit', 'kg', 'kg', 4),
  ('cost_unit', 'ton', 'ton', 5), ('cost_unit', 'ea', 'ea', 6),
  ('cost_unit', 'day', 'day', 7), ('cost_unit', 'job', 'job', 8)
on conflict (category, value) do update set label = excluded.label, sort_order = excluded.sort_order, is_active = true;
