import { useEffect, useState } from 'react';
import { Download, FileText, RefreshCw, Trash2 } from 'lucide-react';

const apiUrl = (import.meta.env.VITE_API_URL ?? '/api/frac').replace(/\/$/, '');
// const apiUrl = (import.meta.env.VITE_API_URL ?? 'http://localhost:3001').replace(/\/$/, '');
type Document = { type: string; name: string | null };
type Submission = { id: string; reference: string | null; well: string | null; well_eug: string | null; job_success_classification: string | null; submitted_by: string | null; documents: Document[] };
type Company = { id: string; name: string };

export function Submissions({ accessToken, onBack, title = 'Submitted frac jobs' }: { accessToken: string; onBack: () => void; title?: string }) {
  const [submissions, setSubmissions] = useState<Submission[]>([]); const [companies, setCompanies] = useState<Company[]>([]); const [companyId, setCompanyId] = useState(''); const [canViewAll, setCanViewAll] = useState(false); const [canManage, setCanManage] = useState(false); const [error, setError] = useState('');
  const load = async (selected = companyId) => { try { const response = await fetch(`${apiUrl}/api/frac-jobs/submissions${selected ? `?companyId=${encodeURIComponent(selected)}` : ''}`, { headers: { Authorization: `Bearer ${accessToken}` } }); const payload = await response.json() as { submissions?: Submission[]; canViewAllCompanies?: boolean; canManageSubmissions?: boolean; message?: string }; if (!response.ok) throw new Error(payload.message ?? 'Unable to load submissions.'); setSubmissions(payload.submissions ?? []); setCanViewAll(payload.canViewAllCompanies === true); setCanManage(payload.canManageSubmissions === true); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load submissions.'); } };
  useEffect(() => { void fetch(`${apiUrl}/api/frac-jobs/submission-companies`, { headers: { Authorization: `Bearer ${accessToken}` } }).then(async (response) => { const payload = await response.json() as { companies?: Company[]; canViewAllCompanies?: boolean }; if (!response.ok) throw new Error('Unable to load companies.'); setCompanies(payload.companies ?? []); setCanViewAll(payload.canViewAllCompanies === true); }).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'Unable to load companies.')); }, [accessToken]);
  useEffect(() => { void load(); }, [accessToken, companyId]);
  const download = async (jobId: string, document: Document) => { try { const response = await fetch(`${apiUrl}/api/frac-jobs/${jobId}/documents/${document.type}/download`, { headers: { Authorization: `Bearer ${accessToken}` } }); if (!response.ok) throw new Error('Unable to open attachment.'); const url = URL.createObjectURL(await response.blob()); window.open(url, '_blank', 'noopener'); window.setTimeout(() => URL.revokeObjectURL(url), 60_000); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to open attachment.'); } };
  const remove = async (jobId: string) => { if (!confirm('Delete this submitted job and its attachment records?')) return; try { const response = await fetch(`${apiUrl}/api/frac-jobs/${jobId}`, { method: 'DELETE', headers: { Authorization: `Bearer ${accessToken}` } }); if (!response.ok) { const payload = await response.json() as { message?: string }; throw new Error(payload.message ?? 'Unable to delete submission.'); } await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to delete submission.'); } };
  return <main className="min-h-screen bg-ink-100 p-4 sm:p-8"><div className="mx-auto max-w-6xl"><header className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-ink-900">{title}</h1><p className="text-sm text-ink-500">Reference, well details, classification, submitter, and attachments.</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={() => void load()}><RefreshCw size={16} /> Refresh</button><button className="btn-primary" onClick={onBack}>Back</button></div></header>{canViewAll && <label className="mb-4 block max-w-md text-sm text-ink-700">Company<select className="field-input mt-1" value={companyId} onChange={(e) => setCompanyId(e.target.value)}><option value="">All companies</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></label>}<div className="card overflow-x-auto p-4"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Reference</th><th>Well</th><th>Well EUG</th><th>Job Success Classification</th><th>Submitted by</th><th>Attachments</th>{canManage && <th>Actions</th>}</tr></thead><tbody>{submissions.map((job) => <tr key={job.id} className="border-b border-ink-100"><td className="p-2">{job.reference ?? '—'}</td><td>{job.well ?? '—'}</td><td>{job.well_eug ?? '—'}</td><td>{job.job_success_classification ?? '—'}</td><td>{job.submitted_by ?? '—'}</td><td className="py-2">{job.documents.length ? job.documents.map((document) => <button key={document.type} className="btn-ghost mr-2" title={document.name ?? 'Report'} onClick={() => void download(job.id, document)}><FileText size={15} /> <Download size={14} /></button>) : '—'}</td>{canManage && <td><button className="btn-ghost text-red-600" title="Delete submission" onClick={() => void remove(job.id)}><Trash2 size={15} /></button></td>}</tr>)}</tbody></table>{!submissions.length && <p className="p-4 text-sm text-ink-500">No submitted jobs found.</p>}</div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}</div></main>;
}
