import { useEffect, useState } from 'react';
import { Pencil, Plus, Trash2 } from 'lucide-react';
import { adminLookups, type Item } from '@/services/adminLookupService';

const apiUrl = (import.meta.env.VITE_API_URL ?? '/api/frac').replace(/\/$/, '');
type User = { id: string; username: string; email: string; company_id: string; company: string; role: 'admin' | 'editor' | 'viewer' };
const empty = { username: '', email: '', password: '', companyId: '', role: 'editor' };

export function AdminUsers({ accessToken, onBack }: { accessToken: string; onBack: () => void }) {
  const [users, setUsers] = useState<User[]>([]); const [companies, setCompanies] = useState<Item[]>([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<User | null>(null); const [error, setError] = useState('');
  const request = async (path: string, init?: RequestInit) => { const response = await fetch(`${apiUrl}${path}`, { ...init, headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json', ...(init?.headers ?? {}) } }); const payload = await response.json().catch(() => ({})) as { message?: string; users?: User[] }; if (!response.ok) throw new Error(payload.message ?? 'User administration request failed.'); return payload; };
  const load = async () => { try { const [payload, companyList] = await Promise.all([request('/api/admin/users'), adminLookups.companies(accessToken)]); setUsers(payload.users ?? []); setCompanies(companyList); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load users.'); } };
  useEffect(() => { void load(); }, [accessToken]);
  const save = async () => { try { if (!form.password) throw new Error('A password is required.'); await request(`/api/admin/users${editing ? `/${editing.id}` : ''}`, { method: editing ? 'PUT' : 'POST', body: JSON.stringify(form) }); setEditing(null); setForm(empty); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save user.'); } };
  const remove = async (id: string) => { if (!confirm('Delete this user?')) return; try { await request(`/api/admin/users/${id}`, { method: 'DELETE' }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to delete user.'); } };
  return <main className="min-h-screen bg-ink-100 p-4 sm:p-8"><div className="mx-auto max-w-6xl"><header className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold text-ink-900">User administration</h1><p className="text-sm text-ink-500">Create users, assign their company and role, then edit or remove them.</p></div><button className="btn-danger" onClick={onBack}>Back</button></header><div className="card p-4"><div className="grid gap-3 md:grid-cols-3"><input className="field-input" placeholder="Username" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} /><input className="field-input" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><input className="field-input" type="password" placeholder="Password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><select className="field-input" value={form.companyId} onChange={(e) => setForm({ ...form, companyId: e.target.value })}><option value="">Select company…</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</select><select className="field-input" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="admin">Admin</option><option value="editor">Editor</option><option value="viewer">Viewer</option></select><button className="btn-danger" onClick={() => void save()}>{editing ? <Pencil size={16} /> : <Plus size={16} />}{editing ? 'Update user' : 'Create user'}</button></div></div><div className="card mt-5 overflow-x-auto p-4"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Username</th><th>Email</th><th>Company</th><th>Role</th><th>Actions</th></tr></thead><tbody>{users.map((user) => <tr key={user.id} className="border-b border-ink-100"><td className="p-2">{user.username}</td><td>{user.email}</td><td>{user.company}</td><td>{user.role}</td><td><button className="btn-ghost" onClick={() => { setEditing(user); setForm({ username: user.username, email: user.email, password: '', companyId: user.company_id, role: user.role }); }}><Pencil size={15} /></button><button className="btn-ghost text-red-600" onClick={() => void remove(user.id)}><Trash2 size={15} /></button></td></tr>)}</tbody></table></div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}</div></main>;
}
